---
title: "Untitled"
author: "George G Vega Yon"
date: "April 5, 2019"
output:
  pdf_document:
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(magrittr)
```

```{r read-the-data}
dat <- readRDS("data/model_data.rds")
```

## Part 1: Descriptive statistics

```{r}
# A function to calculate t-test by variable, by group
vars <- c("age", "male", "sbp", "rr", "gcs")
tstats <- vector("character", length(vars))
ans <- lapply(vars, function(v) {
  tmpdat <- filter(dat, val == 0)
  
  if (v == "male")
    prop.test(table(tmpdat[[v]], tmpdat[["died"]]))
  else
    t.test(tmpdat[[v]][tmpdat[["died"]] == 0], tmpdat[[v]][tmpdat[["died"]] == 1])
})
names(ans) <- vars

# Formating the data
ans <- sapply(ans, function(d) {
  with(d, {
  sprintf("%4.2f %s", statistic,
          case_when(
            p.value < .001 ~ "***",
            p.value < .01  ~ "**",
            p.value < .05   ~ "*",
            TRUE ~ ""
          )
          )
  })
})

# Regular stats ----------------------------------------------------------------
part1 <-
  dat %>%
  filter(val == 0) %>%
  group_by(died) %>%
  summarise(
    `Age`  = sprintf("%.2f (%.2f)", mean(age), sd(age)),
    `Male` = sprintf("%d (%.2f%%)", sum(male), mean(male)*100),
    `SBP (mm Hg)` = sprintf("%.2f (%.2f)", mean(sbp), sd(sbp)),
    `RR (breaths per minute)` = sprintf("%.2f (%.2f)", mean(rr), sd(rr)),
    `Glasgow Coma Scale` = sprintf("%.2f (%.2f)", mean(gcs), sd(gcs))
  )

part1 <- part1 %>%
  rbind(c("Dif of means", ans))

part1 <- t(part1)
colnames(part1) <- c("Survived", "Died", "Dif. in means")
part1 <- part1[-1,]

# Race -------------------------------------------------------------------------
part2 <- dat %>%
  filter(val == 0) %>%
  group_by(died) %>%
  summarize(
    Asian                = sprintf("%d (%.2f%%)", sum(race == 1L), sum(race == 1L)/n()*100),
    `African American`   = sprintf("%d (%.2f%%)", sum(race == 2L), sum(race == 2L)/n()*100),
    `Non-Hispanic white` = sprintf("%d (%.2f%%)", sum(race == 3L), sum(race == 3L)/n()*100),
    `Hispanic white`     = sprintf("%d (%.2f%%)", sum(race == 4L), sum(race == 4L)/n()*100)
  )

# Totals -----------------------------------------------------------------------
part2 <- cbind(t(part2), "")
colnames(part2) <- c("Survived", "Died", "Diff. in means")
part2 <- part2[-1,]
rownames(part2) <- paste0("\\hspace{.5cm}", rownames(part2))

part3 <- dat %>%
  filter(val == 0) %>%
  group_by(died) %>%
  summarize(
    Total = n()
  ) %>% t
part3 <- cbind(part3[-1,, drop=FALSE], "")
colnames(part3) <- NULL

tab <- rbind(
  part1,
  structure(c("", "", ""), class="matrix", dim=c(1, 3), dimnames = list("\\it Ethnicity", NULL)),
  part2,
  part3
  )
knitr::kable(tab, caption = "Descriptive statistics by status (In-hospital mortality). In the case of continuous variables, standard errors are showed in parenthesis, otherwise it shows the proportion within the group. For the significance of the differences $^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$.")
```

## Part 2 - 5: Predictive model

```{r coding-race}
race <- c("Asian", "African American", "Non-Hispanic white", "Hispanic white")
dat$race <- race[dat$race]
dat$race2 <- factor(dat$race, levels = race)
```


```{r model_part2_01, message=FALSE, warning=FALSE}
library(texreg)
# Baseline model
model_part2a_01 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2a_02 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + I(age^2) + male + race + sbp + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2a_07 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + I(sbp ^ 2) + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2a_08 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + I(rr ^ 2) + gcs, data=.,
      family = binomial(link = "logit"))

model_part2a_09 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + I(gcs ^ 2), data=.,
      family = binomial(link = "logit"))

model_part2a_10 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + I(age ^ 2) + male + race + sbp + I(gcs ^ 2), data=.,
      family = binomial(link = "logit"))
```

\blandscape

```{r tabulating, results='asis',}

# New labels for the coefficients
coef_labels <- list(
      age                      = "Age",
      male                     = "Male",
      raceAsian                = "Asian",
      `raceHispanic white`     = "Hispanic white",
      `raceNon-Hispanic white` = "Non-Hispanic white",
      sbp                      = "SBP (mm Hg)",
      rr                       = "RR (breaths per minute)",
      gcs                      = "Glasgow Coma Scale (GCS)",
      `I(age^2)`               = "$\\mbox{Age}^2$",
      `I(sbp^2)`               = "$\\mbox{SBP}^2$",
      `I(rr^2)`                = "$\\mbox{RR}^2$",
      `I(gcs^2)`               = "$\\mbox{GCS}^2$",
      `I(age * gcs)`           = "Age x GCS",
      `I(age * rr)`            = "Age x RR",
      `I(age * male)`          = "Age x Male",
      `I(age * sbp)`           = "Age x SBP",
      `I(male * gcs)`          = "Male x GCS",
      `I(male * rr)`           = "Male x RR",
      `I(male * sbp)`          = "Male x SBP",
      "(Intercept)"            = "(Intercept)"
    )

models <- ls(pattern = "^model\\_part2a")
mget(models) %>%
  set_names(sprintf("(%d)", 1:length(models))) %>%
  texreg(custom.coef.map = coef_labels
  )
```

\elandscape

```{r}
model_part2b_01 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + I(age*male) + male + race + sbp + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2b_02 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + I(age*sbp) + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2b_03 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + I(age*rr) + gcs, data=.,
      family = binomial(link = "logit"))

model_part2b_04 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + rr + I(age*gcs), data=.,
      family = binomial(link = "logit"))

model_part2b_05 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + I(male * sbp) + rr + gcs, data=.,
      family = binomial(link = "logit"))

model_part2b_06 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + I(male * rr) + gcs, data=.,
      family = binomial(link = "logit"))

model_part2b_07 <- dat %>%
  filter(val == 0) %>%
  glm(died ~ age + male + race + sbp + rr + I(male * gcs), data=.,
      family = binomial(link = "logit"))
```

\blandscape

```{r tables-part2, results='asis'}
models <- ls(pattern = "^model\\_part2b")
mget(models) %>%
  set_names(sprintf("(%d)", 1:length(models))) %>%
  texreg(custom.coef.map = coef_labels
  )
```

\elandscape

# Part 6: Provide the model formula for the probability of dying in the hospital

The model with the lowest BIC is model 

```{r bestmodel}
models <- ls(pattern = "^model\\_part")
models <- mget(models)

best_model <- sapply(models, BIC) %>%
  which.min()

best_model <- models[[best_model]]
```

```{r printing-best-model, results='asis'}
best_coefs <- coef(best_model)
names(best_coefs) <- coef_labels[match(names(best_coefs), names(coef_labels))]

# Adding a split in the middle
mid <- ceiling(length(best_coefs) / 2)

cat("\\begin{multline}\n")
best_coefs <- sprintf("%+4.2f \\times \\mbox{%s}", best_coefs, names(best_coefs))
best_coefs[mid] <- paste0(best_coefs[mid], "\\\\")
cat(best_coefs, sep = " ")
cat("\\end{multline}\n")
```

  
\begin{equation}
\Pr{\mbox{die} = 1} = \mbox{logit}^{-1}(X\beta)
\end{equation}

# Part 7: ROC Curves

```{r printing-aucs, message=FALSE, warning=FALSE}
library(AUC)
library(pROC)

# First, we make a prediction
pred <- predict(best_model, type = "response")

# Generating AUC and ROC curve
model_aucs <- ci.auc(as.factor(filter(dat, val == 0)$died), pred)
plot(
  AUC::roc(pred, as.factor(filter(dat, val == 0)$died)),
  main = sprintf(
    "ROC\nAUC of %4.2f [%4.2f; %4.2f CI at the %i%%]", 
    model_aucs[2], model_aucs[1], model_aucs[3], attr(model_aucs, "conf.level")*100
  )
  )
```

# Part 8: Predictions out of sample

```{r}
pred_out_of_sample <- predict(
  best_model,
  newdata = filter(dat, val == 1),
  type    = "response"
  )

# Calculating auc
# Generating AUC and ROC curve
model_aucs <- ci.auc(as.factor(filter(dat, val == 1)$died), pred_out_of_sample)
plot(
  AUC::roc(pred_out_of_sample, as.factor(filter(dat, val == 0)$died)),
  main = sprintf(
    "ROC\nAUC of %4.2f [%4.2f; %4.2f CI at the %i%%]", 
    model_aucs[2], model_aucs[1], model_aucs[3], attr(model_aucs, "conf.level")*100
  )
  )
```

Awfull!

